### ISSUE TITLE
Sprint 3 Team 2: Shop & Saving

### ISSUE THREAD

**Issue by tommps** [UQdeco2800/2021-studio-6#125]
# **Description**
As an important aspect of the game, to ensure all items have a purpose a shop will be included in the game. This shop will allow players to use their money in order to both customise the player and become more prepared for their surroundings. This gives the player higher control of the player and their abilities/functionality. This will include: buying different weapons, buying armours, buying bandages, selecting a different ability.

Additionally, the goal of this feature is to implement the functionality of saving which includes carrying states across between levels. Currently item numbers and states are not carried across levels, therefore it is important that the player has some sort of state carry so that players are able to progress. For saving this will be important to allow players to stop and start again, so that they don't need to restart and lose motivation to play the game.

## Sub Feature/Component
- Carrying states between levels
- Saving the player state every Safehouse entry (and level)
- Sending back to checkpoint upon death
- Design of safehouse "level"
- Designing ability pickups 
- Buying system
- Buying for items (bandage, torch), armor, weapons & abilities [would all fall under a single task]
 
## **Examples**
- **Carrying states:** The game will now keep track and carry player's state forward when progressing towards the end of the game. Number of coins, ammo, bandages and all relevant data will now be carried forward when player completes a level - current version of the game does not do that and player will restart with the basics which may cause users to be frustrated.
- **Saving player state at safehouse:** Currently, when player dies and game is restarted - player will be taken to the very start of the game which is unfair and may cause users to lose motivation. Feature implementation will include having safehouse as a checkpoint. Meaning, player will be taken to the safehouse if player does die after leaving the safehouse (in the following level). This gives player the opportunity to try again and not start from the very beginning of the game.
- **Safehouse design:** Currently, game's safehouse only consist of the door (for which player will collide with and leave for the next level). Alongside an 'interactable' shop where the player will be able to buy items. In addition to this, there will be new walls, furniture, floors, a shopkeeper (for to interact and buy items) and possibly a new door. This is possibly a big revamp will be reviewed and evaluated via user testing.  
- **Buying system:**: Implementation will be similar to the start game screen where after interacting with the shop the user will be shown a new screen where the item, price and short description will be shown. By clicking on each item the player will be able to buy that item.

# **Dependencies**
- Safehouse design
- #61 
 
# **Milestones**
- [x] #138 (23/09)
- [x] #140 (23/09)
- [x] #168  (29/09)
- [x] #157  (29/09)
- [ ]  #159 (30/09)
- ~Saving system (config files) (30/09)~
- [x] #193 (6/10)
- [x] #172 (3/10)
- ~Choosing a saved file to load on opening (5/10)~
- [ ] #202 (5/10)
- [x] User Testing: Shop Screen Structure & Interactions (6/10)
- [x] Finalisation of Documentation (6/10)

Sprint Due date = 7/10

# **Extras**
- Enemy dropping items (coins)

# **Documentation**
- [User Testing: Shop Interactions and Structure](../wiki/https://github.com/UQdeco2800/2021-studio-6/wiki/Sprint-3:-User-Testing-Shop:-Shop-popup-box-and-buying-system)
- [Player State](../wiki/Sprint-3:-Player-State)
- [Safehouse Overview](../wiki/Sprint-3:-Safehouse-Overview)
- [Ability Icon Designs](../wiki/Sprint-3-Design:-Player-Ability-Pickups)
- [Shopkeeper Design](../wiki/Sprint-3-Design:-Shopkeeper) 
- [Shop UI Design](../wiki/Sprint-3-Design:-Shop-Interface) 

# **Members**
- Caitlin Thompson (@tommps) (Caitlin)
- Eric Cheong Kai Kit (@25Ericcheong) (Eric)
- Jing Yang (@ydiannaj)
- Lucas Bouwman (@Bluehalomango)
- Sambit Bhattacharya (@SBHATTA19)
- Anthony Chiam (@ultimate1112)

**Comment by 25Ericcheong** [comment]
Updated feature ticket - there is a difference between maintaining player state (internal memory) and saving system (involves created, deleting and loading a specific file)

**Comment by 25Ericcheong** [comment]
Saving files will no longer be implemented in game. Justification is due to how game is not long enough to justify the amount of effort that needs to be put into managing files and keeping track of player's state with that coherently.

**Comment by tommps** [comment]
EOS
