### ISSUE TITLE
Safehouse - Seamless Interior Ground Tile v2.0

### ISSUE THREAD

**Issue by BungyStudios** [UQdeco2800/2021-studio-6#134]
# **Description**
The current v1.0 ground tile in the safehouse will be redesigned/updated to v2.0.
The tile will be made seamless so that no definable boundaries can be determined between each tile.
 
**Completion Deadline:** 2021/09/21
 
# **Documentation**
- [Safehouse](../wiki/Safehouse/)

**Comment by Bluehalomango** [comment]
Hey, not sure this is for your team anymore. Fairly certain we (Team 2) are handling the shop/safehouse and will also be doing the design of it at the same time so it's not actually a part of your environment/level feature anymore.

**Comment by BungyStudios** [comment]
Have fun
