### ISSUE TITLE
Sprint 3 Team 2: Items & Upgrades

### ISSUE THREAD

**Issue by Bluehalomango** [UQdeco2800/2021-studio-6#139]
# **Description**
Serving as a continuation and extension of items, and partly player, from the previous sprint, this feature is aimed at adding more  to the current implementations. In some cases, this is through breadth by adding more different things and in other cases it is through depth and expansion of existing concepts. The idea behind adding these in is to give the player more freedom and choice in how they play. Adding more things for them to spend money on incentivizes them to explore and save money for better items.

## Sub Feature/Component
- Short range melee weapon upgrade
- Medium range melee weapon upgrade
- Long range melee weapon upgrade
- Ranged weapon upgrade
- Grenade usable/ability
- Mine usable/ability
- Torch item  

## **Examples**
- **Weapon Upgrades** The player will be able to purchase a new and improved weapon at the safehouse between each level if they have enough money. This weapon would have improved stats and a different appearance to inform the player of the significant change.
- **Torch** The torch item is an integral part of the darkness system and is used as a mobile source of lighting to help players through the level and to ward off danger and enemies. The torch is planned to get dimmer as time goes, either requiring players to use another torch or to hasten their actions.
- **Grenade** The player can make use of a grenade ability or usable item against enemies. After being thrown, it will land or stop and explode after several seconds, severely damaging anything nearby. This gives players a limited-use option against tougher enemies or situations.

# **Dependencies**
- #125 For being able to buy the items at the safehouse
- #136 The torch lighting depends on the lighting system used for the darkness and its implementation
 
# **Milestones**
**Code**
- [x] #176 (03/10)
- [x] #200  (03/10)
- [x] #189 (02/10)

**Design**
- [x] #173 (23/09)
- [x] #174  (28/09)
- [x] #175 (03/10)
- [x] #195  (05/10)
- [x] Items Design User Testing. [1](../wiki/Sprint-3---User-Testing-Player:-First-Iteration-Additional-Weapon-Designs) & [2](../wiki/Sprint-3:-User-Testing-Player:-Final-Weapon-Designs) (05/10)
- [x] Finalising Documentation (06/10)

Sprint Due date = 7/10

# **Extras**
- Grenade code redesign (continuation from sprint 2)
- Mine ability/item
- Additional Long ranged weapon upgrade
- Ranged weapon attack animations
- More indepth melee attack system
- Ability upgrades

# **Documentation**
- [User Testing: Initial Upgraded Weapons](../wiki/Sprint-3---User-Testing-Player:-First-Iteration-Additional-Weapon-Designs)
- [User Testing: Final Upgraded Weapons](../wiki/Sprint-3:-User-Testing-Player:-Final-Weapon-Designs)
- [Upgraded Weapon Designs](../wiki/Sprint-3---Upgraded-Weapon-Designs)
- [Unlit Renderer](../wiki/Sprint-3---Unlit-Renderer)
 
# **Members**
- Caitlin Thompson (@tommps) (Caitlin)
- Eric Cheong Kai Kit (@25Ericcheong) (Eric)
- Jing Yang (@ydiannaj)
- Lucas Bouwman (@Bluehalomango)
- Sambit Bhattacharya (@SBHATTA19)
- Anthony Chiam (@ultimate1112)

**Comment by tommps** [comment]
EOS
