### ISSUE TITLE
Bug: Player movement issue while the game is paused

### ISSUE THREAD

**Issue by DancingBrian** [UQdeco2800/2021-studio-6#160]
When the game state is in a paused state (e.g. prologue, pause menu, dialogue box) and the user presses any of the movement keys, when the game is then unpaused the player will run in the opposite direction.

To replicate on the current main branch:
- Start a game and skip the prologue
- Pause the game by pressing ESC
- While on the pause screen press the "w" key
- Unpause the game by clicking "continue", and the player will keep running in the "s" direction

Not sure if this is an issue with the player movement or how pause has been set up, so will label it both Team 1 and Team 2.

**Comment by 25Ericcheong** [comment]
Hi, nice fix. I believe this came from `KeyboardPlayerInputComponent.java` - there wasn't a condition to check if game time was paused or not and all i did was add this condition in. Can't fabricate the bug you've just mentioned - i've created a new branch for this - called `main-bug-solving`. Let me know if its ok on your end. I've created a pull request for this as well.
