### ISSUE TITLE
Bug: Player teleported from start of level 1 to safehouse

### ISSUE THREAD

**Issue by DancingBrian** [UQdeco2800/2021-studio-6#163]
Very rarely the player is teleported from the start of level 1 into the safehouse. I'm not sure what causes this or how to replicate at this stage. Just checking if anyone else has experienced this bug or whether anyone has more information regarding it. 

If no one else is experiencing this issue then I will close this bug at the end of this sprint.

**Comment by 25Ericcheong** [comment]
As in - when the game starts. Do you see Level 1 game area first and then you go into safehouse? Or you go into safehouse straightaway when you start the game. Is this occurring in main now? Never once has this happened to me - let me know if you've managed to replicate it many times in a row

**Comment by DancingBrian** [comment]
> As in - when the game starts. Do you see Level 1 game area first and then you go into safehouse? Or you go into safehouse straightaway when you start the game. Is this occurring in main now? Never once has this happened to me - let me know if you've managed to replicate it many times in a row

Level 1 is created successfully. Then after about 30 seconds of walking around killing monsters the player would get teleported into the inside of the safe house. It has happened a couple of times but I haven't been able to successly replicate it. Next time it happens I will try to recall what I was doing at the time, and keep trying to replicate it.

**Comment by yourlow** [comment]
Hey I think i figured this one out, So we created a new long range enemy type last sprint `tough long range enemy` unfortunately i think that it was implemented with previous code where the bullet teleported the player when it hit the safehouse.

**Comment by DancingBrian** [comment]
> 
> 
> Hey I think i figured this one out, So we created a new long range enemy type last sprint `tough long range enemy` unfortunately i think that it was implemented with previous code where the bullet teleported the player when it hit the safehouse.

Ah nice, yep that could be it. I was wondering whether it was a stray bullet that may of been hitting it. If you have added the fix in, then feel free to close this issue.
