### ISSUE TITLE
Bug: Setting screen is black entirely in main

### ISSUE THREAD

**Issue by 25Ericcheong** [UQdeco2800/2021-studio-6#164]
Start game and go settings. It is black. Was able to trace back to commit ID 55f73c2 (when settings is blacked out totally) and commit ID 7472cde (when you can still see the settings). 1 commit difference

**Comment by DancingBrian** [comment]
Looks like the stage.act() and stage.draw() commands have been removed from the Render method in Renderer class. If you add them back in then the settings appears again. These commands seems to have been removed for the dynamic lighting updates.

**Comment by yourlow** [comment]
rip sorry this was me. That would cause issues with the dynamic lighting @DancingBrian this is an easy fix I can quickly fix this.

**Comment by yourlow** [comment]
fixed in 5735dbb7caf7df53f4eaf7fd104193e82c05d594

**Comment by 25Ericcheong** [comment]
Ah! I missed them ty for looking into it. I thought renderUI gets called somewhere else. Okay - then its all good then - thought it was a bigger underlying issue.
