### ISSUE TITLE
Bug: Player continously walking on entering/leaving the safehouse

### ISSUE THREAD

**Issue by DancingBrian** [UQdeco2800/2021-studio-6#167]
When the player enters/leaves the safehouse (on any level), the player will initially start stationary but as soon you start walking then they continuously walk in the same direction that the player entered the safe house from.

Branch: Main
To replicate:
- Go to the end of level one and position the player below the safehouse
- Hold 'w' to enter the safe house
- When inside the safehouse, press 'd'. The player will now continously walk in the 'w' direction

It is possible that calling the "resetPlayerMovements" trigger might fix this issue so I have assigned the ticket to @25Ericcheong for now.

**Comment by 25Ericcheong** [comment]
I hate this bug so much haha. Created a pull #177 . If any other bug, ping me.

**Comment by kainphoton** [comment]
You can temporary fix this issue by pausing and unpausing the game.

**Comment by 25Ericcheong** [comment]
Solved
