### ISSUE TITLE
Bug: Player health and melee attacks proximity issue

### ISSUE THREAD

**Issue by DancingBrian** [UQdeco2800/2021-studio-6#45]
While testing the latest build I noticed a potential issue with the player taking damage (related task #20). Currently if the enemy is closer than the melee hitbox of the player, the player takes 1 damage, however if the enemy stays in close proximity then the player doesn't continuously take damage (i.e. they could stay alive indefinitely). As the enemy is still near the player, then should the player keep taking damage after a certain time interval? 

A similar proximity issue also seems to occur for the player melee attacks (related task #36), where the melee attacks won't incur additional damage to the enemy if the enemy is stays closer than the player's melee hitbox.

To reproduce it: Constantly walk into a single ghost (or let it push you once it is closer than the melee range)

![image](https://user-images.githubusercontent.com/88139197/131244333-42226f53-ae10-4bd5-97fc-e3ef13d01702.png)

**Comment by 25Ericcheong** [comment]
Yes, this is a bug that was there initially for both NPC (base of the game) and player (in the first pull request). Currently, the task is to ensure that damaged could at least be dealt by player to NPC (at the very least once for sprint 1). As of now, the player's melee attack is currently being improved so that damage can still be dealt regardless if enemy is as close as the image you've shown. Thanks for mentioning!

**Comment by SBHATTA19** [comment]
To add additional updates, the revised solution is that the player is creating a new fixture for each attack. This should at least bypass the attack issue as a collision is created each attack.

**Comment by implex001** [comment]
This may be related but similar behaviour (where no damage can be dealt) can be created when a tree collider is within the attack hit box. Most likely can be solved with the above solution.
![image](https://user-images.githubusercontent.com/20593747/131304425-e4b67fd1-96eb-42af-a204-685576958b75.png)

**Comment by tommps** [comment]
#10 The secondary bug, player being unable to take damage, is an issue with the enemies system for attacking and not the player taking health -> relevant to the enemey feature

**Comment by SpiritBlues7** [comment]
This was fixed in pull request https://github.com/UQdeco2800/2021-studio-6/pull/268
