### ISSUE TITLE
Extra Player Task: Directional Melee Attacks

### ISSUE THREAD

**Issue by SBHATTA19** [UQdeco2800/2021-studio-6#46]
# **Description**
**Task:** Directional Melee Attacks
**Feature:** #8 
 
Ensure that the melee attacks are directional rather than being limited to being defined by a collision box around the player. The fixture for the melee  attack should move based on the player direction. 
   
# **Milestones**
- [x] Ensuring that the melee attack box can be added and removed when movement is triggered (Aug 28)
- [x]  Move player melee attack box based on direction (Sep 1)
**Completion Deadline:** Sep. 1
 
# **Documentation**
- [Player Attacks](../../2021-studio-6/wiki//Player-Attacks)
 
# **Member**
- Sambit Bhattacharya (@SBHATTA19 ) 
- Eric Cheong Kai Kit (@25Ericcheong)

**Comment by tommps** [comment]
end of sprint 1
