### ISSUE TITLE
Bug: Player component seems to be attached to long range enemy bullet

### ISSUE THREAD

**Issue by implex001** [UQdeco2800/2021-studio-6#53]
To reproduce, walk in such a way that the enemy bullet hits the safehouse. The player is then teleported into the safehouse even if they are not near the safehouse. 
Also if the player dies, the camera snaps to a bullet. If that bullet hits the safehouse, the player is respawned inside the safehouse. However, if the resurrected player then tries to exit the safehouse, the game crashes with a segmentation fault.

**Comment by ultimate1112** [comment]
Team 2: Should be fixed by now.
