### ISSUE TITLE
Sprint 2 Team 3: Enemies 

### ISSUE THREAD

**Issue by Hollycatsoulis** [UQdeco2800/2021-studio-6#55]
### Description

The enemies feature was completed in sprint 1 (#10 ) provides a base to work off for sprint 2.  In sprint 1 3 Enemies types were successfully implemented, `small`, `large` and `long-range`. In sprint 2 we plan to expand upon these ideas and add extra features to the enemies.

The _game feel_ of the enemies is currently lacklustre, their actions are somewhat limited and boring, only being able to wander and chase the player. Also the reactions to the player are non-existent, effort will be spent this sprint making enemies more engaging to interact with. This means additions to AI as well as improving the hitboxes and adding reactivity to the animations.

The expansion of the visual design of the current enemies is also planned, animations to all enemies is to be completed in this sprint. In addition to visual design the sound design of enemies will be implemented however, this will most likely require the use of free sound assets as the team has no one skilled in sound design and effort would be most likely wasted in this area.

A final boss is planned for the game the bosses gameplay + visual design will be completed this sprint but depending on time the programming of the final boss may be pushed back to next sprint.

Very little testing was done on the code in the last sprint, this is to be greatly expanded this sprint, all of sprint 1 features will need to be tested as well as future work 

### Examples / Sub Feature Component
- Expanded AI 
- animation
- sound
- mocking
- unit tests

### Dependencies

(Environment) the implementation of the darkness is heavily dependant on the 
(player) Interactions with the enemies is heavily dependant on what is added or changed about the player

### Programming
- [x] Enemy Spawners
- [x] New long range enemy
- [x] Better enemy reactivity
- [x] Improved enemy hitboxes
- [x] Testing
- [ ] Drop coins/pickups when enemies are killed

### Design

- [ ] Animations 
- [ ] Walking Animations
- [ ] Attack Animations
- [ ] Idle Animation
- [x] Spawner Graphic 
- [ ] Sound effects – royalty free

### Documentation
Lighting Wiki
Darkness gameplay Wiki

### Members
- Matt (@yourlow) (Matthew Holloway)
- Nik (@nikmatha) (Niklas Matha)
- Hamish (@Hamish-Killen) (Hamish Killen)
- Jade (@jadeomikaela) (Jade Taylan)
- Crystal (@quartz-c) (Crystal Yu) 
- Holly (@Hollycatsoulis) (Holly Catsoulis)

**Comment by tommps** [comment]
The enemy's bullets do not get deleted when colliding with the game boundary and therefore don't get deleted, will likely need to fix during this sprint to avoid having too many bullets spawned into the game area at any given time
