### ISSUE TITLE
Bug: Safehouse related bugs

### ISSUE THREAD

**Issue by Bluehalomango** [UQdeco2800/2021-studio-6#71]
- Sometimes when entering the safehouse, the player is frozen and cannot move
- Sometimes the player will be immediately teleported out of the safehouse without interacting with anything
- Occasionally when exiting/entering the safehouse or dying, the user is sent back to the title screen. Hard to replicate, mainly just chance. Chances are, this is an issue due to how Team 2 and 5 implemented dying and that interaction with bullets having the player component.
- Bullets collidle weirdly in the safehouse (Weird physics, moving in different directions, moving at different speeds, caught on random walls) 
- Weird frame issue (can be seen as a sort of sprite 'ticking' when moving)
- Occasionally gets shot to the right when entering the safehouse. Sticks around until user closes the games. (Hard to replicate)
- Sometimes crashes when entering/exiting safehouse

**Comment by Bluehalomango** [comment]
Some issues can be resolved by disabling player attack in the safehouse, specifically the bullet collisions.

**Comment by implex001** [comment]
With the teleporting into and out of the safehouse, it seems that the player component somehow is attached to the bullet components **OR** the safe house is looking for a collision from anything, not just the player. So when an enemy shoots a bullet into the safehouse the player is teleported into it. This can also happen when the player dies in the world and a bullet then manages to hit the safehouse. The player is then respawned, possibly without the player input component but somehow with some other kind of movement component or none at all (which could explain @Bluehalomango's first dot point).
I've mentioned this issue in #53.

**Comment by Bluehalomango** [comment]
> With the teleporting into and out of the safehouse, it seems that the player component somehow is attached to the bullet components **OR** the safe house is looking for a collision from anything, not just the player. So when an enemy shoots a bullet into the safehouse the player is teleported into it. This can also happen when the player dies in the world and a bullet then manages to hit the safehouse. The player is then respawned, possibly without the player input component but somehow with some other kind of movement component or none at all (which could explain @Bluehalomango's first dot point).
> I've mentioned this issue in #53.

That explains the teleporting in but this bug report was more specifically about being teleported out of the safehouse, as that seems unrelated to the bullets (there shouldn't be any enemy bullets in the safehouse to trigger collision) although the lack of movement is probably related. Also this bug report was made to try and consolidate issues surrounding the safehouse and other interactions so some of the issues here might relate elsewhere.

**Comment by 25Ericcheong** [comment]
For bullets. It currently has player layer - which explains why when bullet hits safehouse you get teleported to the next level and also explains why camera focuses on enemy's bullet when player dies since player gets disposed and I believe camera tries to look for the next current existing player layer in the game (in this case, the bullets)

**Comment by Bluehalomango** [comment]
Added Team 5 to assignees because safehouse mainly falls under your feature.

**Comment by tommps** [comment]
Added an event for disabling attacks which will be pushed in our next push to main (before next studio) -> so issues with attacking in safehouse shouldn't be a problem (but probably still worth adding testing and figuring out why its having issues)

**Comment by 25Ericcheong** [comment]
Found 2 possible causes for crashing when exiting safehouse (colliding with the door). Possibly due to something not being disposed of properly and the game still progressing to create something on top of that.

![SafehousePossibleBugError2](https://user-images.githubusercontent.com/55186326/132962416-6e2f4214-d8d3-4839-8f47-e0ab2428785b.PNG)
![SafehousePossibleBugError1](https://user-images.githubusercontent.com/55186326/132962418-f2836b9e-751e-49d1-95da-85e2fa19b17e.PNG)

**Comment by Lumin-cider** [comment]
> With the teleporting into and out of the safehouse, it seems that the player component somehow is attached to the bullet components **OR** the safe house is looking for a collision from anything, not just the player. So when an enemy shoots a bullet into the safehouse the player is teleported into it. This can also happen when the player dies in the world and a bullet then manages to hit the safehouse. The player is then respawned, possibly without the player input component but somehow with some other kind of movement component or none at all (which could explain @Bluehalomango's first dot point).
> I've mentioned this issue in #53.

With the teleport mechanism, the safehouse is attached to the player layer, and so is the enemy bullet, this could mean that since both are looking for the player layer, they somehow can also be looking for each other?

**Comment by Lumin-cider** [comment]
> Found 2 possible causes for crashing when exiting safehouse (colliding with the door). Possibly due to something not being disposed of properly and the game still progressing to create something on top of that.
> 
> ![SafehousePossibleBugError2](https://user-images.githubusercontent.com/55186326/132962416-6e2f4214-d8d3-4839-8f47-e0ab2428785b.PNG)
> ![SafehousePossibleBugError1](https://user-images.githubusercontent.com/55186326/132962418-f2836b9e-751e-49d1-95da-85e2fa19b17e.PNG)

I've had this kind of error message before, and this crash occurred outside of JVM, JVM crashes can be caused by external components, either something directly used by the running software or indirectly related, for instance, virus protection or other system software.
As for the asset not loaded, I will try and replicate the bug and see what is happening with the asset not loaded.
