### ISSUE TITLE
Bug: Title screen buttons Null pointer exception 

### ISSUE THREAD

**Issue by yourlow** [UQdeco2800/2021-studio-6#72]
On the title screen if you mouse over one of the buttons right when the window boots up it throws a null pointer exception. This doesn't happen on earlier versions this could be due to the music.

**Comment by DancingBrian** [comment]
Wow good pickup! Looks like the bug has something to do with the button rollover listener. Will see if I can find what is causing the crash.

**Comment by DancingBrian** [comment]
This error looks to have occurred when the element that was being rolled over returned null. I have added a null check within the rollover logic so this crash should not occur anymore. Can you please confirm whether this new fix removes the crash for you in the latest version of main?

**Comment by yourlow** [comment]
yep seems to haved fixed it!
